openapi: "3.0.3"
info:
  title: FusionAuth API (public)
  version: "1"
externalDocs:
  description: Оригинальная документация
  url: https://fusionauth.io/docs/apis/
servers:
  - url: http://localhost:9091/
  - url: https://identity.imsha.by/
tags:
  - name: FusionAuthApi
    description: FusionAuth сервер
paths:
  /api/passwordless/send:
    $ref: 'resource/passwordless/send.yaml#/paths/~1api~1passwordless~1send'
  /api/passwordless/login:
    $ref: 'resource/passwordless/login.yaml#/paths/~1api~1passwordless~1login'
