# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4af9609
_src_path: https://github.com/ImshaBy/ci_cd_template
build_args: false
domain: api.imsha.by
namespace: backend
project_name: imshaby-api
