version: '3'

services:
  imshaby-api:
    image: cr.yandex/crp8o64j2cl644b4pjki/imshaby-api:028db99391db33bd9372220be1fe566059debbf4
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoadmin:HHPebl16917@158.160.45.142:27017/imshaby?authSource=admin
      SPRING_PROFILES_ACTIVE: develop
      PASSWORDLESS_API_KEY: "yyyyryryry"
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
    #   - /home/yc-user/coi-data:/data

# x-yc-disks:
#   - device_name: coi-data
#     fs_type: ext4
#     host_path: /home/yc-user/coi-data
