server:
  port: 3000
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  profiles:
    active: "dev"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/imshaby"
      auto-index-creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  web:
    locale: "be_BY"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:https://localhost:9091/.well-known/jwks.json}

app:
  imsha:
    default-city:
      name: "Minsk"
    lang-cookie: "i_lang"
    web-hook-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5VTTJSamd6UTBReE5ESXlNelU1UWtWRU5USkdPRVl4TlRFNFJrVTFSREF6UlRWRE9ETTROQSJ9.eyJpc3MiOiJodHRwczovL2ltc2hhLmF1dGgwLmNvbS8iLCJzdWIiOiJOZHZneTlQazhwUUlLN1FVVWtzVHI3ZU1oUUl4S1R1SEBjbGllbnRzIiwiYXVkIjoiYm90Lmltc2hhLmJ5IiwiaWF0IjoxNjE3MTkwNTA3LCJleHAiOjE2MTcyNzY5MDcsImF6cCI6Ik5kdmd5OVBrOHBRSUs3UVVVa3NUcjdlTWhRSXhLVHVIIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.OGduCg169Jvw457OyHza5_p-xHB4SfrIapYk9NCBHBurAZpaKiIx4FDQ81p8Li2c7iYbrq9Jq5-8eru7zu-dO0ZPfwzZn32_BpGkbmq3OAShcT__5pa-76K6_YFd7z-SEZgtTSwEGUg0GzXkQqz-dLe4DVEV8V84ufwGkfyOxIUKV7SQS1GYaQTKJeR2xyp5I2h3ROeOMnUPwECPrDDkHSzpXHVxXj5bEG6GhPOaQ3xgeYbO2TFGLEZt-QIMCWQw_KP4Oq7-KzmZ5Vk691lvbPe-pNZNEcpUURFclSt-qtJLsBpC3wPcDbHvzw5qo7ZCTsX4OKzIg4Y3W-aRM0CD6g
  cors:
    allow-credentials: true
    allowed-origins:
      - "http://localhost:8080"
      - "http://localhost:4200"
      - "http://localhost:5556"
      - "http://localhost"
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
  oauth2:
    passwordless:
      application-id: ${PASSWORDLESS_APPLICATION_ID:adf0a804-0f48-43d9-a43c-566d377d8fcb}
      api-key: ${PASSWORDLESS_API_KEY}
      uri:
        start: ${PASSWORDLESS_URI_START:https://localhost:9091/api/passwordless/login}
        send: ${PASSWORDLESS_URI_SEND:https://localhost:9091/api/passwordless/send}
        login: ${PASSWORDLESS_URI_LOGIN:https://localhost:9091/api/passwordless/login}
