spring:
  data:
    mongodb:
      uri: "mongodb://imshaby:imshaby123@mongodb48105-api-imshaby.mycloud.by/api"

app:
  cors:
    allowed-origins:
      - "*"
      - "http://qa.imsha.by"
      - "https://qa.imsha.by"
      - "https://admin.qa.imsha.by"
      - "http://imsha.mycloud.by"
      - "http://localhost:4200"
      - "http://localhost:8080"
      - "http://localhost:3000"
