spring:
  data:
    mongodb:
      uri: "mongodb://admin:Hvd6jxKpiF@mongodb54373-beta-api-imsha.mycloud.by/api?authSource=admin"

app:
  cors:
    allowed-origins:
      - "http://beta.imsha.by"
      - "https://beta.imsha.by"
      - "http://beta-web-imsha.mycloud.by"
