spring:
  data:
    mongodb:
      uri: "mongodb://admin:LXAyrf52412@mongodb53235-prod-api-imsha.mycloud.by/api?authSource=admin"
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
app:
  cors:
    allowed-origins:
      - "http://imsha.by"
      - "https://imsha.by"
      - "https://admin.imsha.by"
      - "http://prod-web-imsha.mycloud.by"
      - "http://www.imsha.by"
      - "https://www.imsha.by"
      - "https://yc.imsha.by"
      - "https://do.imsha.by"
      - "https://new.imsha.by"
      - "https://www.yc.imsha.by"
      - "https://www.new.imsha.by"
      - "https://www.admin.yc.imsha.by"
      - "https://www.admin.do.imsha.by"
      - "https://admin.do.imsha.by"
      - "https://app.nutricio.org"
      - "https://www.kosteluzda.by"