server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO

#http://localhost:8080/swagger-ui/index.html
#http://localhost:8080/v3/api-docs - json
#http://localhost:8080/v3/api-docs.yaml - yaml
springdoc:
  swagger-ui:
    enabled: true

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/imshaby"
      auto-index-creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  web:
    locale: "be_BY"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:https://localhost:9091/.well-known/jwks.json}

app:
  imsha:
    default-city:
      key: "minsk"
    lang-cookie: "i_lang"
    web-hook-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5VTTJSamd6UTBReE5ESXlNelU1UWtWRU5USkdPRVl4TlRFNFJrVTFSREF6UlRWRE9ETTROQSJ9.eyJpc3MiOiJodHRwczovL2ltc2hhLmF1dGgwLmNvbS8iLCJzdWIiOiJOZHZneTlQazhwUUlLN1FVVWtzVHI3ZU1oUUl4S1R1SEBjbGllbnRzIiwiYXVkIjoiYm90Lmltc2hhLmJ5IiwiaWF0IjoxNjE3MTkwNTA3LCJleHAiOjE2MTcyNzY5MDcsImF6cCI6Ik5kdmd5OVBrOHBRSUs3UVVVa3NUcjdlTWhRSXhLVHVIIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.OGduCg169Jvw457OyHza5_p-xHB4SfrIapYk9NCBHBurAZpaKiIx4FDQ81p8Li2c7iYbrq9Jq5-8eru7zu-dO0ZPfwzZn32_BpGkbmq3OAShcT__5pa-76K6_YFd7z-SEZgtTSwEGUg0GzXkQqz-dLe4DVEV8V84ufwGkfyOxIUKV7SQS1GYaQTKJeR2xyp5I2h3ROeOMnUPwECPrDDkHSzpXHVxXj5bEG6GhPOaQ3xgeYbO2TFGLEZt-QIMCWQw_KP4Oq7-KzmZ5Vk691lvbPe-pNZNEcpUURFclSt-qtJLsBpC3wPcDbHvzw5qo7ZCTsX4OKzIg4Y3W-aRM0CD6g
    # empty by default, add them via environment (aaa, bbb,ccc ,ddd,eee) - spaces insensitive
    api-keys: ${API_KEYS:}
    internal-api-keys: ${INTERNAL_API_KEYS:}
    zone-id: Europe/Minsk
    parish-week-api-keys: ${PARISH_WEEK_API_KEYS:}
  cors:
    allow-credentials: true
    allowed-origins:
      - "http://localhost:8080"
      - "http://localhost:4200"
      - "http://localhost:5556"
      - "http://localhost"
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
  oauth2:
    passwordless:
      log-code: ${PASSWORDLESS_LOG_CODE:false}
      application-id: ${PASSWORDLESS_APPLICATION_ID:adf0a804-0f48-43d9-a43c-566d377d8fcb}
      api-key: ${PASSWORDLESS_API_KEY}
      uri:
        start: ${PASSWORDLESS_URI_START:https://localhost:9091/api/passwordless/start}
        send: ${PASSWORDLESS_URI_SEND:https://localhost:9091/api/passwordless/send}
        login: ${PASSWORDLESS_URI_LOGIN:https://localhost:9091/api/passwordless/login}
  auth:
    confirmation-code-email-template-id: 1ab56274-46f5-4023-b585-e5334585f820
    uri:
      send-email: https://identity.imsha.by/api/email/send

meilisearch:
  reader:
    host-url: http://localhost:7700
    api-key: 8Yy6fAZCCIPDiQk4yay7_xrHoxconfRKC5HKhuoij8o
    index-uid: mass-index

fusionAuth:
  host-url: https://identity.imsha.by
  authorization-token: LVkhGbFBTQuvnZgm3OCgS3uAGHJ55QZBxh43GN94RZ6aLDW2pZL2bUo8
  user-search-pagination: 10
  application-id: 1f99412a-b65b-4acf-87f7-1dc21d93b127

fusionAuthApi:
  url: https://identity.imsha.by
