name: 'redis-clone-action'
description: 'redis dump-restore'
inputs:
  source:
    description: 'source redis url ( format: redis://1.1.1.1:6379 )'
    required: true
  target:
    description: 'target redis url ( format: redis://2.2.2.2:6379 )'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download rump file and do some magic
      run : |
        sudo apt install -y curl
        curl -SL https://github.com/stickermule/rump/releases/download/1.0.0/rump-1.0.0-linux-amd64 -o rump && chmod +x rump;
        ./rump -from ${{ inputs.source }} -to ${{ inputs.target }}
      shell: bash
branding:
  icon: 'server'
  color: 'gray-dark'