version: '3'

services:
  imshaby-api:
    image: ${DOCKER_API_IMAGE}
    environment:
      MONGODB_URI: ${MONGODB_URI}
      CORS_URLS: ${CORS_URLS}
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
    #   - /home/yc-user/coi-data:/data

# x-yc-disks:
#   - device_name: coi-data
#     fs_type: ext4
#     host_path: /home/yc-user/coi-data