version: '3'

services:
  imshaby-api:
    image: ${DOCKER_API_IMAGE}
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PASSWORDLESS_API_KEY: ${PASSWORDLESS_API_KEY}
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
    #   - /home/yc-user/coi-data:/data

# x-yc-disks:
#   - device_name: coi-data
#     fs_type: ext4
#     host_path: /home/yc-user/coi-data