logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO

app:
  imsha:
    zone-id: Europe/Minsk

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/imshaby"
      auto-index-creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

meilisearch:
  writer:
    host-url: http://localhost:7700
    api-key: 8Yy6fAZCCIPDiQk4yay7_xrHoxconfRKC5HKhuoij8o
    index-uid: mass-index

fusionauth:
  application-id: 1f99412a-b65b-4acf-87f7-1dc21d93b127
  url: https://identity.imsha.by
  security:
    apiKey:
      key: LVkhGbFBTQuvnZgm3OCgS3uAGHJ55QZBxh43GN94RZ6aLDW2pZL2bUo8
  user-search-pagination: 10