# Default values for imshaby-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecret: acr-auth
image:
  repository: local/imshaby-api
  tag: v1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

activeProfile: local

mongodb:
  host: mongodb
  port: 27017
  database: api
  user: api_admin
  password: api_admin

service:
  type: ClusterIP
  port: 3000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}