{{- if .Values.workloads }}
{{- range $wName, $w := .Values.workloads }}
{{- if (($w.serviceAccount | default dict).create) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (($w.serviceAccount | default dict).name | default (include "workload.fullname" (dict "ctx" $ "name" $wName))) }}
  labels:
    {{- include "workload.labels" (dict "ctx" $ "name" $wName) | nindent 4 }}
  annotations:
    {{- toYaml (($w.serviceAccount | default dict).annotations | default dict) | nindent 4 }}
  {{- if (($w.serviceAccount | default dict).automountServiceAccountToken) }}
automountServiceAccountToken: {{ ($w.serviceAccount | default dict).automountServiceAccountToken }}
  {{- end }}
{{- end }}
{{- end }}
{{- else }}
{{- if (.Values.serviceAccount | default dict).create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-app.serviceAccountName" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml (.Values.serviceAccount | default dict).annotations | nindent 4 }}
  {{- if (.Values.serviceAccount | default dict).automountServiceAccountToken }}
automountServiceAccountToken: {{ (.Values.serviceAccount | default dict).automountServiceAccountToken }}
  {{- end }}
{{- end }}
{{- end }}
