# This is a basic workflow to help you get started with Actions

name: Copy MongoDB data (erase target db data)

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceUri:
        type: choice
        description: Select SOURCE DB_URI secret
        options:
        # Only from prod and mycloud qa (the list will grow)
        - PROD_MONGODB_URI
        - QA_MYCLOUD_MONGODB_URI
      targetUri:
        type: choice
        description: Select TARGET DB_URI secret
        options:
        # Only to YC qa (the list will grow)
        - QA_YC_MONGODB_URI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mongo-clone-action"
  mongo-clone-action:
    runs-on: ubuntu-22.04
    name: Clone MongoDB
    steps:
    - uses: Maggi64/mongo-clone-action@0.3
      with:
        source: ${{ secrets[github.event.inputs.sourceUri] }}
        target: ${{ secrets[github.event.inputs.targetUri] }}
