name: Artillery Load Test

on:
  push:
    branches: [redisson-cache]

jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make reports directory
        run: mkdir reports

      - name: Execute load tests
        run: /home/node/artillery/bin/run run --target https://api2.qa.imsha.by --output reports/report.json perf/artillery.yml

      - name: Generate HTML report
        run: /home/node/artillery/bin/run report --output reports/report reports/report.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*