# This is a basic workflow to help you get started with Actions

name: Deploy Image to Yandex Cloud Compute Instance

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ terraform-yc ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLI_PATH: iac/tf
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - run: yc config list

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
#      - run: pwd && cd iac/tf


      - run: pwd && cd iac/tf && terraform init

#      - id: plan
#        run: cd iac/tf && terraform plan --var-file ../envs/production.tfvars -no-color
      - run: export YC_TOKEN=$(yc iam create-token) export YC_CLOUD_ID=$(yc config get cloud-id) export YC_FOLDER_ID=$(yc config get folder-id)
      - run: echo ${YC_TOKEN}
      - run: echo ${YC_CLOUD_ID}
      - run: echo ${YC_FOLDER_ID}


#      - run: echo ${{ steps.plan.outputs.stdout }}
#      - run: echo ${{ steps.plan.outputs.stderr }}
#      - run: echo ${{ steps.plan.outputs.exitcode }}

#      - name: Build, tag, and push image to Yandex Cloud Container Registry
#        env:
#          CR_REGISTRY: crp8o64j2cl644b4pjki
#          CR_REPOSITORY: imshaby-api
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
#          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
