name: Release QA

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  deploy_qa:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: start remote ansible file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.QA_SSH_HOST}}
          username: ${{vars.QA_SSH_USER}}
          password: ${{secrets.QA_SSH_PASSWORD}}
          key: ${{secrets.QA_SSH_KEY}}
          script: |
            cd /root/imshaby-deploy
            ansible-playbook ./staging.yaml --extra-vars "service_name=backend api_tag=${{ needs.create_tag.outputs.tag }} api_url=${{ vars.VITE_API_URL }} spring_profile=${{ vars.QA_SPRING_PROFILE}}"
